sudo: false
language: generic
cache:
  timeout: 360
  directories:
  - "$HOME/.stack/"
  - "$HOME/.local/bin/"
  - ".stack-work/"
install:
- mkdir -p ~/.local/bin
- export PATH=$HOME/.local/bin:$PATH
- travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
jobs:
  include:
    - stage: install whoami
      if: branch = master
      script: stack --no-terminal --stack-yaml ./stack.yaml install whoami
    - stage: exec whoami
      if: branch = master
      script: git clone -b master "https://${GH_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git" temp
      after_success:
        - cd temp
        - stack exec -- whoami -o README.md -t markdown whoami.yaml
        - git config user.name "${GIT_NAME}"
        - git config user.email "${GIT_EMAIL}"
        - git status
        - git add -A
        - git diff --quiet && git diff --staged --quiet || git commit -am "[skip ci] Update whoami"
        - git push origin master
